#!/bin/sh
while [ $# -gt 0 ]; do
	case "$1" in
	-fg | -bg | -fn)
		XArg="$XArg $1"
		shift
		XArg="$XArg \"$1\""
		;;
	*)
		SArg="$SArg \\\"$1\\\""
		;;
	esac
	shift
done
Cmd="xterm $XArg -T \"sc $SArg\" -e \"sc $SArg\""
#echo $Cmd
eval $Cmd
